
package presentacion;
import javax.swing.JLabel;
import java.awt.*;
import javax.swing.JButton;


public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    private final Modelo modelo;
    private Controlador control;
    private JLabel lblCajon[][];
    private JLabel informacion[];

    public VistaPrincipal(Modelo aThis) {
        modelo = aThis;
        initComponents();
        initCajones();
        capturarEventos();   
    }

    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }
    
    public Modelo getModelo() {
        return modelo;
    }
        
    public JButton getBtn1() {
        return btn1;
    }
    
    public JButton getBtn2() {
        return btn2;
    }
     
    public JButton getBtn3() {
        return btn3;
    }
    
    public JButton getBtn4() {
        return btn4;
    }
    
    public JButton getBtn5() {
        return btn5;
    }
    
    public JButton getBtn6() {
        return btn6;
    }
    
    public JButton getBtn7() {
        return btn7;
    }
    
    public JButton getBtn8() {
        return btn8;
    }
    public JButton getBtn9() {
        return btn9;
    }
    public void fontLblResultado(boolean resultado) {
        if(resultado == true){
            lblResultado.setForeground(Color.green);
            Font fuente = new Font("Comic Sans MS", Font.BOLD,15);
            lblResultado.setFont(fuente);
        }else{
            lblResultado.setForeground(Color.black);
            Font fuente = new Font("Arial", Font.ITALIC,12);
            lblResultado.setFont(fuente);
        }
    }
    public JLabel getLblResultado() {
        return lblResultado;
    }

  
    private void capturarEventos() {
        btn1.addMouseListener(getControl());
        btn2.addMouseListener(getControl());
        btn3.addMouseListener(getControl());
        btn4.addMouseListener(getControl());
        btn5.addMouseListener(getControl());
        btn6.addMouseListener(getControl());
        btn7.addMouseListener(getControl());
        btn8.addMouseListener(getControl());
        btn9.addMouseListener(getControl());
    }
 
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setBackground(new java.awt.Color(20, 161, 240));

        btn1.setBackground(new java.awt.Color(153, 153, 255));
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(153, 153, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(153, 153, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(153, 153, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(153, 153, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(153, 153, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(153, 153, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(153, 153, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(153, 153, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                                    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handlre:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables

    private void initCajones() {
        int i,j,posX,posY,s=1,w=30;
        lblCajon= new JLabel[9][9];
        informacion= new JLabel[5];
        
        for(byte k=0; k<5;k++){
            informacion[k]= new JLabel();
            informacion[k].setSize(55,23);
            informacion[k].setOpaque(true);
            switch (k){ //Información
                case 0:
                    informacion[k].setSize(155,23);
                    informacion[k].setOpaque(false);
                    informacion[k].setText("Sudoku");
                    informacion[k].setLocation(195, 301);
                    Font font = new Font("Showcard Gothic", Font.BOLD,18);
                    informacion[k].setFont(font);
                    break;
                case 1:
                    
                    informacion[k].setSize(130,70);
                    informacion[k].setText("Marcador de errores: ");
                    informacion[k].setLocation(80, 365);
                    break;
                case 2:
                    informacion[k].setText(" Columna");
                    informacion[k].setLocation(210, 390);
                    informacion[k].setBackground(new java.awt.Color(255, 233, 192));
                    break;
                case 3:
                    informacion[k].setText("      Fila");
                    informacion[k].setLocation(270, 390);
                    informacion[k].setBackground(new java.awt.Color(255, 192, 192));
                    break;
                case 4:
                    informacion[k].setText("   Región");
                    informacion[k].setLocation(330, 390);
                    informacion[k].setBackground(new java.awt.Color(192, 192, 255));
                    break;
            }
            
            this.getContentPane().add(informacion[k]);
        }
        
        for(i=0;i<9;i++){
            for(j=0;j<9;j++){ //Se coloca cada JLabel 

                lblCajon[i][j]= new JLabel();
                lblCajon[i][j].setSize(w,w);
                posX=90+i*(w+s);
                posY=20+j*(w+s);
                lblCajon[i][j].setLocation(posX, posY);
                lblCajon[i][j].setBackground(new java.awt.Color(255, 255, 255));
                 if(((i<3 && j<3) || (i>5 && j<3)) ||((i>2 && j>2) && (i<6 && j<6)) || ((i<3 && j>5) || (i>5 && j>5))){
                    lblCajon[i][j].setBackground(new java.awt.Color(200, 200, 200));
                }
                lblCajon[i][j].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                lblCajon[i][j].setOpaque(true);
                
                
                this.getContentPane().add(lblCajon[i][j]);
            }
        }   
        
    }
    public void mouseLabel(int i, int j){ //Se coloca el listener cuando se invoque 
        lblCajon[i][j].addMouseListener(getControl());
    }
    public JLabel getLblCajon(int i, int j) {
        return lblCajon[i][j];
    }

    public void setLblCajon(int i, int j,String texto) { //se colocan los datos del sudoku o plantilla
        lblCajon[i][j].setForeground(Color.RED);
        lblCajon[i][j].setText(texto);
    }
    
    
    public int[][] getLblMatriz() { //Se envia la matriz apartir de los datos de los JLabel
        String auxString;
        int [][] matriz = new int[9][9];
        for(byte i=0; i<9; i++){
            for(byte j=0; j<9; j++){
                if(lblCajon[i][j].getText()!=""){
                    auxString = lblCajon[i][j].getText();
                    matriz[i][j]=Integer.parseInt(auxString);
                }
            }
        }
        return matriz;
    }

    public void repintar(int i, int j, int color) { //pinta dependiendo del error
        switch(color){
            case -1:
                lblCajon[i][j].setBackground(new java.awt.Color(255, 233, 192));
                break;
            case -2:
                lblCajon[i][j].setBackground(new java.awt.Color(255, 192, 192));
                break;
            case -3:
                lblCajon[i][j].setBackground(new java.awt.Color(192, 192, 255));
                break;
            case -4:
                lblCajon[i][j].setBackground(new java.awt.Color(255, 255, 255));
                if(((i<3 && j<3) || (i>5 && j<3)) ||((i>2 && j>2) && (i<6 && j<6)) || ((i<3 && j>5) || (i>5 && j>5))) {
                    lblCajon[i][j].setBackground(new java.awt.Color(200, 200, 200));
                }
                break;
        }
                
    }   
}


